// Temporary shim to unify types during migration
export type {
  Flashcard,
  StandardMCQCard,
  CompareContrastCard,
  DragAndDropSortingCard,
  FillInTheBlankCard,
  ShortAnswerCard,
  TwoTierMCQCard,
  CERCard,
  SequencingCard,
  Deck,
  Topic,
  DeckProgress,
  GlobalProgress,
  UserXpStats,
  BloomLevel,
  BloomMastery,
  UserPowerUps,
  PowerUpType,
  PurchaseCounts,
  CardFormat,
  UserSettings,
  UserCustomizations,
  SelectedCustomizations,
  UserInventory,
  ShopItem
} from '@/types';
